=== shafr/PortMaster-New/schema/v2_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "items_opt": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      ]
    },
    "attr": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        },
        "inst": {
          "type": "string"
        },
        "genres": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "porter": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "image": {
          "anyOf": [
            {
              "type": [
                "null",
                "string"
              ]
            },
            {
              "type": "object",
              "properties": {
                "screenshot": {
                  "type": "string"
                },
                "cover": {
                  "type": "null"
                },
                "thumbnail": {
                  "type": "null"
                },
                "video": {
                  "type": "null"
                }
              }
            }
          ]
        },
        "rtr": {
          "type": "boolean"
        },
        "runtime": {
          "anyOf": [
            {
              "type": [
                "null",
                "string"
              ]
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "reqs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "arch": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exp": {
          "type": "boolean"
        },
        "inst_md": {
          "type": [
            "null",
            "string"
          ]
        },
        "url": {
          "type": "string"
        },
        "desc_md": {
          "type": "null"
        }
      },
      "required": [
        "desc",
        "genres",
        "image",
        "inst",
        "porter",
        "reqs",
        "rtr",
        "runtime",
        "title"
      ]
    },
    "status": {
      "type": "object",
      "properties": {
        "source": {
          "type": "string"
        },
        "md5": {
          "type": [
            "null",
            "string"
          ]
        },
        "status": {
          "type": "string"
        }
      },
      "required": [
        "md5",
        "source",
        "status"
      ]
    },
    "files": {
      "type": "object",
      "properties": {
        "port.json": {
          "type": "string"
        },
        "Carmageddon.sh": {
          "type": "string"
        },
        "carmageddon": {
          "type": "string"
        },
        "Doom 3.sh": {
          "type": "string"
        },
        "doom3/": {
          "type": "string"
        },
        "Jazz2 Resurrection.sh": {
          "type": "string"
        },
        "jazz2": {
          "type": "string"
        },
        "Klorets.sh": {
          "type": "string"
        },
        "klorets": {
          "type": "string"
        },
        "openxcom/": {
          "type": "string"
        },
        "OpenXcomEX.sh": {
          "type": "string"
        }
      }
    }
  },
  "required": [
    "attr",
    "items",
    "items_opt",
    "name",
    "version"
  ]
}

=== shafr/PortMaster-New/ports/jaggedalliance2/port.json
{
  "version": 4,
  "name": "jaggedalliance2.zip",
  "items": [
    "Jagged Alliance 2.sh",
    "jaggedalliance2"
  ],
  "items_opt": [],
  "attr": {
    "title": "Jagged Alliance 2",
    "porter": [
      "RoyalJupiter"
    ],
    "desc": "Jagged Alliance 2 is strategy game where you lead a group of mercenaries on the island state of Arulco, against the army of the evil Queen Deirdranna.",
    "desc_md": null,
    "inst": "You must have an updated copy of the original Jagged Alliance 2 game files. Copy the retail game's data into the `ports/jaggedalliance2/game` folder. The GOG version of the game is also supported. Download the installer from GOG (https://www.gog.com/en/game/jagged_alliance_2), place it into the `ports/jaggedalliance2` folder, and it will install the game files as required. ",
    "inst_md": null,
    "genres": [
      "strategy"
    ],
    "image": null,
    "rtr": false,
    "exp": false,
    "runtime": [],
    "store": [
      {
        "name": "GOG",
        "gameurl": "\"https://www.gog.com/en/game/jagged_alliance_2",
        "developerurl": ""
      },
      {
        "name": "Jagged Alliance 2 Stracciatella",
        "gameurl": "https://ja2-stracciatella.github.io/",
        "developerurl": ""
      }
    ],
    "availability": "paid",
    "reqs": [
      "power"
    ],
    "arch": [
      "aarch64"
    ],
    "min_glibc": ""
  }
}

=== shafr/PortMaster-New/ports/jazz2/port.json
{
    "version": 2,
    "name": "jazz2.zip",
    "items": [
        "Jazz2 Resurrection.sh",
        "jazz2"
    ],
    "items_opt": null,
    "attr": {
        "title": "Jazz2 Resurrection",
        "porter": [
            "Orson"
        ],
        "desc": "Jazz2 Resurrection is a complete reimplementation of Jazz Jackrabbit 2, a superb 2D platformer, a sequel to Epic Megagames' earlier shareware classic Jazz Jackrabbit (also available in PortMaster).",
        "inst": "Let the intro play the first time you start the game, so it creates cache files. Copy the original game files (The Secret Files and/or The Christmas Chronicles) to ports/jazz2/Source.",
        "genres": [
            "platformer"
        ],
        "image": null,
        "rtr": false,
        "runtime": null,
        "reqs": [],
        "arch": [
            "aarch64",
            "x86_64"
        ]
    },
    "status": {
        "source": "Unknown",
        "md5": null,
        "status": "Installed"
    },
    "files": {
        "port.json": "jazz2/jazz2.port.json",
        "Jazz2 Resurrection.sh": "Jazz2 Resurrection.sh",
        "jazz2": "jazz2"
    }
}

=== shafr/PortMaster-New/ports/jediacademy/port.json
{
    "version": 2,
    "name": "jediacademy.zip",
    "items": [
        "JediAcademy/",
        "Star Wars Jedi Knight - Jedi Academy.sh"
    ],
    "items_opt": null,
    "attr": {
        "title": "Star Wars Jedi Knight - Jedi Academy",
        "desc": "An open source port of Jedi Academy using OpenJK by the JACoders team. Originally developed by Raven Software.",
        "inst": "You need to add your own full game pak files to the ports/JediAcademy/base folder.",
        "genres": [
            "fps"
        ],
        "porter": [
            "brooksytech"
        ],
        "image": {},
        "rtr": false,
        "runtime": null,
        "reqs": [
            "power"
        ],
        "arch": [
            "aarch64"
        ]
    }
}
