=== shafr/PortMaster-New/schema/v4_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "items_opt": {
      "type": ["array", "null"]
    },
    "attr": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "porter": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "Christian_Haitian",
              "Cebion",
              "romadu",
              "Johnny on Flame",
              "Bamboozler",
              "kloptops",
              "Overflask",
              "Nuxx",
              "Jetup",
              "Tekkenfede",
              "nl255",
              "Orson",
              "Slayer366",
              "krishenriksen",
              "brooksytech",
              "jtothebell",
              "TheGammaSqueeze",
              "Snoopy",
              "tabreturn",
              "mattyj513",
              "MadShmupper",
              "Shark",
              "Jeod",
              "wesam",
              "Fraxinus88",
              "Kompaan",
              "Joyrider3774",
              "JanTrueno",
              "Troidem",
              "Consumerism",
              "MegaStriker",
              "Pridetoons",
              "nkahoang",
              "fexofenadine",
              "Damian2809",
              "Zehmaluco",
              "Black_Hand",
              "nate_____",
              "Slobters",
              "kotzebuedog",
              "Ganimoth",
              "Doronimmo",
              "BinaryCounter",
              "NotYourAveragePaladin"
            ]
          }
        },
        "desc": {
          "type": "string"
        },
        "desc_md": {
          "type": ["null", "string"]
        },
        "inst": {
          "type": "string"
        },
        "inst_md": {
          "type": ["null", "string"]
        },
        "genres": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "action",
              "adventure",
              "arcade",
              "casino/card",
              "fps",
              "platformer",
              "puzzle",
              "racing",
              "rhythm",
              "rpg",
              "simulation",
              "sports",
              "strategy",
              "visual novel",
              "other"
            ]
          }
        },
        "image": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "object",
              "properties": {
                "screenshot": {
                  "type": "string"
                },
                "covers": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "thumbnail": {
                  "type": "null"
                },
                "video": {
                  "type": "null"
                }
              }
            }
          ]
        },
        "rtr": {
          "type": "boolean"
        },
        "exp": {
          "type": "boolean"
        },
        "runtime": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "mesa_pkg_0.1.squashfs",
                  "mono-6.12.0.122-aarch64.squashfs",
                  "pyxel_2.2.8_python_3.11.squashfs",
                  "renpy_8.3.4.squashfs",
                  "rlvm.squashfs",
                  "solarus-1.6.5.squashfs",
                  "weston_pkg_0.2.squashfs",
                  "frt_2.1.6.squashfs",
                  "frt_3.0.6_v1.squashfs",
                  "frt_3.1.2.squashfs",
                  "frt_3.2.3.squashfs",
                  "frt_3.3.4.squashfs",
                  "frt_3.4.5.squashfs",
                  "frt_3.5.2.squashfs",
                  "frt_3.6.squashfs",
                  "frt_4.0.4.squashfs",
                  "frt_4.1.3.squashfs",
                  "zulu11.48.21-ca-jdk11.0.11-linux.aarch64.squashfs",
                  "zulu17.48.15-ca-jdk17.0.10-linux.aarch64.squashfs",
                  "zulu17.54.21-ca-jre17.0.13-linux.squashfs"
                ]
              }
            }
          ]
        },
        "reqs": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "arch": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "min_glibc": {
          "type": "string"
        },
        "store": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "gameurl": {
                    "type": "string"
                  },
                  "developerurl": {
                    "type": "string"
                  },
                  "url": {
                    "type": "string"
                  }
                },
                "required": ["name", "gameurl"]
              }
            }
          ]
        },
        "availability": {
          "type": "string"
        },
        "free": {
          "type": "boolean"
        }
      },
      "required": [
        "arch",
        "desc",
        "desc_md",
        "exp",
        "genres",
        "image",
        "inst",
        "min_glibc",
        "porter",
        "reqs",
        "rtr",
        "title"
      ]
    }
  },
  "required": ["version", "name", "attr", "items", "items_opt"]
}

=== shafr/PortMaster-New/ports/alwayssurrender/port.json
{
  "version": 4,
  "name": "alwayssurrender.zip",
  "items": [
    "Always Surrender.sh",
    "alwayssurrender"
  ],
  "items_opt": [],
  "attr": {
    "title": "Always Surrender",
    "porter": [
      "Ganimoth"
    ],
    "desc": "Always Surrender is a vertically scrolling shoot 'em up score attack, with an emphasis on pushing your luck as far as you can. Last as long as possible against an endless horde of enemies and then surrender in order to bank the bonus. Giving up has never been so rewarding. Battle a never ending swarm of enemies, but be sure to surrender before you die...",
    "desc_md": null,
    "inst": "Purchase the game on Steam and copy all game files into the assets folder.",
    "inst_md": "Purchase the game on [Steam](https://store.steampowered.com/app/1434200/Always_Surrender/) and copy all game files into the `assets` folder.",
    "genres": [
      "action"
    ],
    "image": null,
    "rtr": false,
    "exp": false,
    "runtime": [],
    "store": [
      {
        "name": "Steam",
        "gameurl": "https://store.steampowered.com/app/1434200/Always_Surrender/",
        "developerurl": "https://store.steampowered.com/search/?developer=The%20Covert%20Sheep%20Example"
      }
    ],
    "availability": "paid",
    "reqs": [],
    "arch": [
      "aarch64"
    ],
    "min_glibc": ""
  }
}

=== shafr/PortMaster-New/ports/astoryaboutbirds/port.json
{
  "version": 4,
  "name": "astoryaboutbirds.zip",
  "items": [
    "A Story About Birds.sh",
    "astoryaboutbirds"
  ],
  "items_opt": [],
  "attr": {
    "title": "A Story About Birds",
    "porter": [
      "Slobters"
    ],
    "desc": "The birds are coming back! So, gather some wood, some bird food, and build some amazing shelters. \nExplore Plumage Farm on a relaxing day, collect branches and seeds in form of a minigame that requires skill and get to know its inhabitants and regulars. \nHow will you use the day?",
    "desc_md": null,
    "inst": "Install port files. Buy game in Itch. Download \"asab-linux-v1.0.5.zip\" then extract file \"a-story-about-birds.arm64\" into \"ports\\astoryaboutbirds\" folder",
    "inst_md": null,
    "genres": [
      "adventure",
      "rhythm"
    ],
    "image": null,
    "rtr": false,
    "exp": false,
    "runtime": [
      "weston_pkg_0.2.squashfs"
    ],
    "store": [
      {
        "name": "Itch.io",
        "gameurl": "https://partnano.itch.io/a-story-about-birds",
        "developerurl": "https://partnano.itch.io/"
      }
    ],
    "availability": "paid",
    "reqs": [],
    "arch": [],
    "min_glibc": ""
  }
}

=== shafr/PortMaster-New/ports/donthide/port.json
{
  "version": 4,
  "name": "donthide.zip",
  "items": [
    "Dont Hide.sh",
    "donthide"
  ],
  "items_opt": [],
  "attr": {
    "title": "Don't Hide",
    "porter": [
      "NotYourAveragePaladin"
    ],
    "desc": "Trapped in a maze with a beast, you must find five keys and their door to escape. The monster can only smell and hear you, but as long as it hasn't fully caught your scent, you can move freely.",
    "desc_md": null,
    "inst": "Download the game For Free from Steam: https://store.steampowered.com/app/2131620/Dont_Hide/\nOr\nFrom Itch.io:\nhttps://sulfic-games.itch.io/dont-hide\nand Copy the DontHideGame.pck file into the gamedata folder",
    "inst_md": null,
    "genres": [
      "strategy"
    ],
    "image": null,
    "rtr": false,
    "exp": false,
    "runtime": [
      "frt_3.3.4.squashfs"
    ],
    "store": [
      {
        "name": "Steam",
        "gameurl": "https://store.steampowered.com/app/2131620/Dont_Hide/",
        "developerurl": "https://store.steampowered.com/search/?developer=Sulfic%20Games"
      },
      {
        "name": "itch.io",
        "gameurl": "https://sulfic-games.itch.io/dont-hide",
        "developerurl": "https://sulfic-games.itch.io/"
      }
    ],
    "availability": "free",
    "reqs": [],
    "arch": [],
    "min_glibc": ""
  }
}
